require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - db/schema.rb
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - bin/*

### Rails

Rails:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false


### Bundler

Bundler/OrderedGems:
  Enabled: false


### Metrics

Metrics/AbcSize:
  Max: 20
  Exclude:
    - db/migrate/20170707122626_create_visits.rb
    - db/migrate/20170708054041_install_blazer.rb

Metrics/BlockLength:
  Max: 150

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/20170707122626_create_visits.rb
    - db/migrate/20170708054041_install_blazer.rb


### Style

Style/AutoResourceCleanup:
  Enabled: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Encoding:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/RegexpLiteral:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/MixinUsage:
  Enabled: false

Style/StderrPuts:
  Enabled: false


### Layout

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 140

### Documentation

Style/Documentation:
  Enabled: false
