require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

describe PostsController do
  # This should return the minimal set of attributes required to create a valid
  # Post. As you add validations to Post, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title:   'Foo',
      content: 'Lorem ipsum'
    }
  end

  let(:invalid_attributes) do
    {
      title:   '',
      content: ''
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      create(:post, valid_attributes)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      post = create(:post, valid_attributes)
      get :show, params: { id: post.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    before do
      sign_in_as(build(:admin))
    end

    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    before do
      sign_in_as(build(:admin))
    end

    it "returns a success response" do
      post = create(:post, valid_attributes)
      get :edit, params: { id: post.to_param }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    before do
      sign_in_as(build(:admin))
    end

    context "with valid params" do
      it "creates a new Post" do
        expect do
          post :create, params: { post: valid_attributes }, session: valid_session
        end.to change(Post, :count).by(1)
      end

      it "redirects to the created post" do
        post :create, params: { post: valid_attributes }, session: valid_session
        expect(response).to redirect_to(Post.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { post: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    before do
      sign_in_as(build(:admin))
    end

    context "with valid params" do
      let(:new_attributes) do
        {
          title: 'Bar'
        }
      end

      it "updates the requested post" do
        post = create(:post, valid_attributes)
        put :update, params: { id: post.to_param, post: new_attributes }, session: valid_session
        post.reload
        expect(post.title).to eq('Bar')
      end

      it "redirects to the post" do
        post = create(:post, valid_attributes)
        put :update, params: { id: post.to_param, post: valid_attributes }, session: valid_session
        expect(response).to redirect_to(post)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        post = create(:post, valid_attributes)
        put :update, params: { id: post.to_param, post: invalid_attributes }, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    before do
      sign_in_as(build(:admin))
    end

    it "destroys the requested post" do
      post = create(:post, valid_attributes)
      expect do
        delete :destroy, params: { id: post.to_param }, session: valid_session
      end.to change(Post, :count).by(-1)
    end

    it "redirects to the posts list" do
      post = create(:post, valid_attributes)
      delete :destroy, params: { id: post.to_param }, session: valid_session
      expect(response).to redirect_to(posts_url)
    end
  end
end
